- name: demo on registry variable
  hosts: all
  tasks:
    - name: run uptime shell command
      ansible.builtin.shell: uptime
      register: output
    - name: print output
      ansible.builtin.debug:
        msg: "{{ output.start }}"
