- name: Install golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Include task list in play
  ansible.builtin.import_tasks:
    file: add_user.yml

- name: Install and build golang dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: start systemd service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_start