- name: Loading mongo schema
  when: setup_schema == "mongo"
  block:
    - name: setup and copy mongodb repo file
      ansible.builtin.template:
       src: mongo.repo
       dest: /etc/yum.repos.d/mongo.repo
       remote_src: yes

    - name: Install mongodb client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: schema loading
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', '{{ env }}.{{ component }}.mongo_endpoint', region='us-east-1' ) }} </app/schema/{{component}}.js



